### ISSUE TITLE
Example out of date?

### ISSUE THREAD

**Issue by nomeata** [qfpl/reflex-dom-canvas#1]
I was about to try your library, following the example in https://github.com/qfpl/reflex-dom-canvas/blob/master/examples/src/CanvasTest3D.hs but it uses a function `CDyn.drawCanvasFree` in this line:
```
  (eInitFailed, eRenderMeh) <- fanEither <$> CDyn.drawCanvasFree dInitProg dGLCX eInit
```
which, it seems, was removd in https://github.com/qfpl/reflex-dom-canvas/commit/e4806d20fb6123322f9c074e8007c18b699c484f. How would the example look today?

**Comment by mankyKitty** [comment]
The examples are out of date, sorry about that. Off the top of my head I think this function: https://github.com/qfpl/reflex-dom-canvas/blob/master/src/Reflex/Dom/CanvasDyn.hs#L162 would do what you need.

That being said, I'm not convinced the `Free` based API was a terribly good idea. I would recommend using the jsaddle API functions directly and using this package to manage the context and applying the instructions.

I'll leave this open until I update the examples.

**Comment by nomeata** [comment]
I ended up writing my own little brother of your package (as my use-case is more specific):
https://github.com/nomeata/reflex-dom-fragment-shader-canvas
but thanks for the inspiration!

**Comment by mankyKitty** [comment]
Nice! You can use the functions listed here https://hackage.haskell.org/package/jsaddle-dom-0.9.2.0/docs/JSDOM-Generated-WebGL2RenderingContext.html in place of the stringly ones that you have. You simply pass in the gl context as the first input to most of them. :) :+1: I lurk in #reflex-frp on freenode if you're around.

**Comment by nomeata** [comment]
Yeah, switching to `jsaddle-dom` is on my TODO list – the first version was using just plain `jsaddle`, but now that I also pull in `reflex-dom` I guess I am already depending on `jsaddle-dom`.

**Comment by mankyKitty** [comment]
Don't use `jsaddle-dom` the package. Use the `ghcjs-dom` package as that is what `reflex-dom` depends on. It's just that the documentation is better for the `jsaddle-dom` package, but `ghcjs-dom` handles the details of supporting both GHC and GHCJS environments.
