### ISSUE TITLE
Examples only with ghcjs?

### ISSUE THREAD

**Issue by nomeata** [qfpl/reflex-dom-canvas#2]
The examples cabal file says:
```
  if !impl(ghcjs -any)
    buildable: False
```
Is there a good reason for why the examples would not work with `jsaddle-warp`, during local development?

**Comment by mankyKitty** [comment]
I suspect that is from before I knew about the `jsaddle-warp` dev process. The thinking behind it was that if you're not building with GHCJS then you're not going to have the Canvas in a form that is recognisable by this package. 

I'll fix that up in the next release. :+1:
